<li class="clearfix"> <a href="[field:typeurl/]"> <span>1</span>
              <div class="div1"><img src="[field:litpic /]">
                <div class="rname">
                  <h3>[field:fulltitle/]</h3>
                  <p>点击下载</p>
                </div>
              </div>
              <div class="div2" style="display:none;">
                <h4>[field:fulltitle/]</h4>
              </div>
              </a> </li>