<li class="clearfix"> <a href="#"> <span>1</span>
              <div class="div1"><img src="{dede:global.cfg_templets_skin/}/images/shiwan/pic2.jpg">
                <div class="rname">
                  <h3>应用猎人</h3>
                  <p>点击下载</p>
                </div>
              </div>
              <div class="div2" style="display:none;">
                <h4>应用猎人</h4>
              </div>
              </a> </li>