<?php
$z[0]=Array("global","",105,132);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",144,176);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",223,249);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",568,593);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\n      	",632,873);
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[5]=Array("global","",961,986);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("tag","\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\n          ",1779,1907);
$z[6][4]['row']="10";
$z[6][4]['getall']="1";
$z[6][4]['sort']="month";

?>