<?php
$z[0]=Array("global","",233,261);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",273,299);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",342,372);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",408,435);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",452,484);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",613,641);
$z[5][4]['name']="cfg_mobileurl";
$z[6]=Array("global","",1119,1147);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("include","",1263,1298);
$z[7][4]['filename']="head.htm";
$z[8]=Array("channelartlist","\n   <dl class=\"tbox\">\n    <dt><strong><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></strong><span class=\"more\"><a href=\"{dede:field name='typeurl'/}\">更多...</a></span></dt>\n    <dd>\n     <ul class=\"d1 ico3\">\n      {dede:arclist titlelen='60' row='8'}\n      <li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>\n      {/dede:arclist}\n     </ul>\n    </dd>\n   </dl>\n   ",1379,1878);
$z[9]=Array("include","",1908,1945);
$z[9][4]['filename']="footer.htm";

?>