<?php
$z[0]=Array("global","",681,713);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1081,1113);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1155,1187);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channel","\r\n            <li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n          ",1400,1662);
$z[3][4]['row']="10";
$z[3][4]['type']="top";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<li class='nactive'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>